CREATE TABLE users (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,

    email VARCHAR(100) UNIQUE NOT NULL,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash VARCHAR(255),

    auth_provider ENUM('LOCAL','GOOGLE','FIREBASE') NOT NULL,
    provider_user_id VARCHAR(100),

    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    UNIQUE (auth_provider, provider_user_id)
);